In [2]:
import numpy as np

A = np.random.rand(3,4)*100

print(A)

[[88.11943296 43.44686122 64.89844322 50.43781506]
 [80.48123804 87.7168167  50.71808362 89.51561872]
 [49.47702565 34.88145389 86.73125412 83.07845316]]


In [9]:
cal = A.sum(axis=0)
print(cal)

[218.07769665 166.04513181 202.34778096 223.03188695]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[40.40735679 26.16569408 32.07272297 22.61462061]
 [36.90484597 52.8270933  25.06480841 40.13579401]
 [22.68779724 21.00721262 42.86246862 37.24958538]]


In [15]:
a = np.random.rand(5,1)
print(a)

[[0.47307743]
 [0.41740111]
 [0.73632934]
 [0.18882627]
 [0.66795077]]


In [16]:
print(a.shape)

(5, 1)


In [17]:
print(a.T)

[[0.47307743 0.41740111 0.73632934 0.18882627 0.66795077]]


In [19]:
print(np.dot(a,a.T))

[[0.22380225 0.19746304 0.34834079 0.08932944 0.31599244]
 [0.19746304 0.17422368 0.30734468 0.07881629 0.27880339]
 [0.34834079 0.30734468 0.5421809  0.13903832 0.49183175]
 [0.08932944 0.07881629 0.13903832 0.03565536 0.12612665]
 [0.31599244 0.27880339 0.49183175 0.12612665 0.44615824]]


In [25]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (4, 1)
c = a*b